-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 21:33:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_main` DEFAULT CHARACTER SET utf8 ;
USE `db_main` ;

-- -----------------------------------------------------
-- Table `db_main`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`statistics` (
  `idstatistics` INT NOT NULL AUTO_INCREMENT,
  `rat_equipment` INT NULL,
  `rat_commisioning` INT NULL,
  PRIMARY KEY (`idstatistics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `organization` VARCHAR(200) NOT NULL,
  `adress` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(100) NOT NULL,
  `contract` VARCHAR(45) NOT NULL,
  `statistics_idstatistics` INT NOT NULL,
  PRIMARY KEY (`idcustomer`),
  INDEX `fk_customer_statistics_idx` (`statistics_idstatistics` ASC) VISIBLE,
  CONSTRAINT `fk_customer_statistics`
    FOREIGN KEY (`statistics_idstatistics`)
    REFERENCES `db_main`.`statistics` (`idstatistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`customer_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`customer_contact` (
  `idcustomer_contact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idcustomer_contact`),
  INDEX `fk_customer_contact_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_customer_contact_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `db_main`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`position` (
  `idposition` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idposition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`commisioning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`commisioning` (
  `idcommisioning` INT NOT NULL AUTO_INCREMENT,
  `act_commisioning` BLOB NULL,
  `act_foundation` BLOB NULL,
  `inspection_report` BLOB NULL,
  PRIMARY KEY (`idcommisioning`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`equipment` (
  `idequipment` INT NOT NULL AUTO_INCREMENT,
  `type_eq` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `ser_number` VARCHAR(100) NOT NULL,
  `cnc_type` VARCHAR(45) NOT NULL,
  `archiv_PLC` BLOB NULL,
  `check_list` BLOB NULL,
  `documentation` BLOB NULL,
  `customer_idcustomer` INT NOT NULL,
  `commisioning_idcommisioning` INT NOT NULL,
  PRIMARY KEY (`idequipment`),
  INDEX `fk_equipment_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  INDEX `fk_equipment_commisioning1_idx` (`commisioning_idcommisioning` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `db_main`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_commisioning1`
    FOREIGN KEY (`commisioning_idcommisioning`)
    REFERENCES `db_main`.`commisioning` (`idcommisioning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`trouble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`trouble` (
  `idtrouble` INT NOT NULL AUTO_INCREMENT,
  `discription` VARCHAR(500) NOT NULL,
  `troubleshooting` VARCHAR(500) NOT NULL,
  `equipment_idequipment` INT NOT NULL,
  PRIMARY KEY (`idtrouble`),
  INDEX `fk_trouble_equipment1_idx` (`equipment_idequipment` ASC) VISIBLE,
  CONSTRAINT `fk_trouble_equipment1`
    FOREIGN KEY (`equipment_idequipment`)
    REFERENCES `db_main`.`equipment` (`idequipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `position_idposition` INT NOT NULL,
  PRIMARY KEY (`idemployee`),
  INDEX `fk_employee_position1_idx` (`position_idposition` ASC) VISIBLE,
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`position_idposition`)
    REFERENCES `db_main`.`position` (`idposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_main`.`commisioning_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_main`.`commisioning_has_employee` (
  `commisioning_idcommisioning` INT NOT NULL,
  `employee_idemployee` INT NOT NULL,
  PRIMARY KEY (`commisioning_idcommisioning`, `employee_idemployee`),
  INDEX `fk_commisioning_has_employee_employee1_idx` (`employee_idemployee` ASC) VISIBLE,
  INDEX `fk_commisioning_has_employee_commisioning1_idx` (`commisioning_idcommisioning` ASC) VISIBLE,
  CONSTRAINT `fk_commisioning_has_employee_commisioning1`
    FOREIGN KEY (`commisioning_idcommisioning`)
    REFERENCES `db_main`.`commisioning` (`idcommisioning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commisioning_has_employee_employee1`
    FOREIGN KEY (`employee_idemployee`)
    REFERENCES `db_main`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
