-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 19:11:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema main_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main_DB` DEFAULT CHARACTER SET utf8 ;
USE `main_DB` ;

-- -----------------------------------------------------
-- Table `main_DB`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`position` (
  `idposition` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idposition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `position_idposition` INT NOT NULL,
  PRIMARY KEY (`idemployee`),
  INDEX `fk_employee_position_idx` (`position_idposition` ASC) VISIBLE,
  CONSTRAINT `fk_employee_position`
    FOREIGN KEY (`position_idposition`)
    REFERENCES `main_DB`.`position` (`idposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`statistics` (
  `idstatistics` INT NOT NULL AUTO_INCREMENT,
  `rat_commisioning` INT NULL,
  `rat_equipment` INT NULL,
  PRIMARY KEY (`idstatistics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `organization` VARCHAR(200) NOT NULL,
  `adress` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(100) NOT NULL,
  `contract` VARCHAR(45) NOT NULL,
  `statistics_idstatistics` INT NOT NULL,
  PRIMARY KEY (`idcustomer`),
  INDEX `fk_customer_statistics1_idx` (`statistics_idstatistics` ASC) VISIBLE,
  CONSTRAINT `fk_customer_statistics1`
    FOREIGN KEY (`statistics_idstatistics`)
    REFERENCES `main_DB`.`statistics` (`idstatistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`commision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`commision` (
  `idcommision` INT NOT NULL AUTO_INCREMENT,
  `act_commision` BLOB NOT NULL,
  `act_foundation` BLOB NOT NULL,
  `inspection_report` BLOB NOT NULL,
  PRIMARY KEY (`idcommision`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`equipment` (
  `idequipment` INT NOT NULL AUTO_INCREMENT,
  `type_eq` VARCHAR(45) NOT NULL,
  `ser_number` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `cnc_type` VARCHAR(45) NOT NULL,
  `archiv_PLC` BLOB NOT NULL,
  `geometry` BLOB NOT NULL,
  `functions` BLOB NOT NULL,
  `documentation` BLOB NOT NULL,
  `commision_idcommision` INT NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idequipment`),
  INDEX `fk_equipment_commision1_idx` (`commision_idcommision` ASC) VISIBLE,
  INDEX `fk_equipment_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_commision1`
    FOREIGN KEY (`commision_idcommision`)
    REFERENCES `main_DB`.`commision` (`idcommision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `main_DB`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`trouble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`trouble` (
  `idtrouble` INT NOT NULL AUTO_INCREMENT,
  `troubleshooting` VARCHAR(500) NOT NULL,
  `trouble_scan` BLOB NULL,
  `equipment_idequipment` INT NOT NULL,
  PRIMARY KEY (`idtrouble`),
  INDEX `fk_trouble_equipment1_idx` (`equipment_idequipment` ASC) VISIBLE,
  CONSTRAINT `fk_trouble_equipment1`
    FOREIGN KEY (`equipment_idequipment`)
    REFERENCES `main_DB`.`equipment` (`idequipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`customer_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`customer_contact` (
  `idcustomer_contact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `phone` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idcustomer_contact`),
  INDEX `fk_customer_contact_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_customer_contact_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `main_DB`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_DB`.`commision_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main_DB`.`commision_has_employee` (
  `commision_idcommision` INT NOT NULL,
  `employee_idemployee` INT NOT NULL,
  PRIMARY KEY (`commision_idcommision`, `employee_idemployee`),
  INDEX `fk_commision_has_employee_employee1_idx` (`employee_idemployee` ASC) VISIBLE,
  INDEX `fk_commision_has_employee_commision1_idx` (`commision_idcommision` ASC) VISIBLE,
  CONSTRAINT `fk_commision_has_employee_commision1`
    FOREIGN KEY (`commision_idcommision`)
    REFERENCES `main_DB`.`commision` (`idcommision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commision_has_employee_employee1`
    FOREIGN KEY (`employee_idemployee`)
    REFERENCES `main_DB`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
